#!/data/data/com.termux/files/usr/bin/bash

CYAN='\033[1;36m'
BLUE='\033[1;34m'
WHITE='\033[1;37m'
RESET='\033[0m'

while true
do

clear
echo -e "${BLUE}☁ ☁ ☁ ☁ ☁ ☁ ☁${RESET}"
echo ""
echo -e "${CYAN}✈${RESET}"
echo ""
echo -e "${WHITE}SKY AIRLINES${RESET}"
sleep 0.15

clear
echo -e "${BLUE}☁ ☁ ☁ ☁ ☁ ☁ ☁${RESET}"
echo ""
echo -e "${CYAN}    ✈${RESET}"
echo ""
echo -e "${WHITE}SKY AIRLINES${RESET}"
sleep 0.15

clear
echo -e "${BLUE}☁ ☁ ☁ ☁ ☁ ☁ ☁${RESET}"
echo ""
echo -e "${CYAN}        ✈${RESET}"
echo ""
echo -e "${WHITE}SKY AIRLINES${RESET}"
sleep 0.15

clear
echo -e "${BLUE}☁ ☁ ☁ ☁ ☁ ☁ ☁${RESET}"
echo ""
echo -e "${CYAN}            ✈${RESET}"
echo ""
echo -e "${WHITE}SKY AIRLINES${RESET}"
sleep 0.15

clear
echo -e "${BLUE}☁ ☁ ☁ ☁ ☁ ☁ ☁${RESET}"
echo ""
echo -e "${CYAN}                ✈${RESET}"
echo ""
echo -e "${WHITE}SKY AIRLINES${RESET}"
sleep 0.15

done
